services:
  backend:
    volumes:
      - ./backend/:/app/
      - /home/nils/Notes/:/localfiles/:ro
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST:-host.docker.internal:11434}
      - CHROMA_DB_URL=${CHROMA_DB_URL:-http://chromadb:8000}
      - SEARXNG_DOMAIN=${SEARXNG_DOMAIN:-http://searxng:8080}
      - EMBEDDINGS_MODEL_NAME=${EMBEDDINGS_MODEL_NAME:-nomic-embed-text:v1.5}
      - VERSION=${VERSION:-dev}
    networks:
      - llm_network_dev
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PUBLIC_VERSION=dev
    volumes:
      - ./:/app/
    ports:
      - '3000:5173'
    networks:
      - llm_network_dev

  chromadb:
    image: chromadb/chroma
    networks:
      - llm_network_dev
    # attach: false
    # logging:
    #   driver: none

  redis:
    image: docker.io/library/redis:alpine
    command: redis-server --save 30 1 --loglevel warning
    networks:
      - searxng
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    image: docker.io/searxng/searxng:latest
    networks:
      - searxng
      - llm_network_dev
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '1'

networks:
  llm_network_dev:
    driver: bridge
  searxng:
    ipam:
      driver: default

volumes:
  redis-data:
