cache_dir: ./.cache/colly
host_delay: 1000ms
allowed_languages:
  - en
embeddings:
  base_url: http://localhost:11434
  # model: qwen3-embedding
  model: qwen3-embedding:4b
  dimensions: 2560
  # model: nomic-embed-text-v2-moe
  # dimensions: 256
  timeout: 30s
  queue_size: 2
  batch_size: 1
websites:
  - https://go-colly.org
  - https://book.kubebuilder.io
  - https://www.flatcar.org
  - https://wiki.nixos.org
  - https://ghostty.org
  - https://docs.k3s.io
  - https://kubernetes.io
  - https://docs.wiit-cloud.io
  - https://gobyexample.com
